MovieReview/config/routes.rb
Rails.application.routes.draw do
  # nested route to associate review with movie
  resources :movies do
    resources :reviews
  end
  root 'movies#index'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
end

MovieReview/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MovieReview/app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movies
  has_many :users, through: :movies
end

MovieReview/app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_many :reviews

  has_attached_file :movie_img, styles: { movie_index: "200x280>", movie_show: "300x420>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :movie_img, content_type: /\Aimage\/.*\z/
end

MovieReview/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

MovieReview/app/models/user.rb
class User < ApplicationRecord
  has_many :movies
  has_many :reviews
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: URI::MailTo::EMAIL_REGEXP, message: "only allows valid emails" },
    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

MovieReview/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

MovieReview/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :find_movie, only: [:show, :edit, :update, :destroy]

  def index
    if params[:genre].blank?
      @movies = Movie.all.order("created_at DESC")
    else
      @genre_id = Genre.find_by(name: params[:genre])
      @movies = Movie.where(:genre_id => @genre_id).order("created_at DESC")
    end
  end

  def show
    if @movie.reviews.blank?
      @average_review = 0
    else
      @average_review = @movie.reviews.average(:rating).round(2)
    end
  end

  def new
    if logged_in?
      @movie = current_user.movies.build
      @genres = Genre.all.map{ |g| [g.name, g.id] }
    else
      redirect_to root_path
    end
  end

  def create
    @movie = current_user.movies.build(movie_params)
    @movie.genre_id = params[:genre_id]
    if @movie.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    if logged_in?
      @genres = Genre.all.map{ |g| [g.name, g.id] }
    else
      redirect_to root_path
    end
  end

  def update
    @movie.genre_id = params[:genre_id]
    if @movie.update(movie_params)
      redirect_to movie_path(@movie)
    else
      render 'edit'
    end
  end

  def destroy
    @movie.destroy
    redirect_to root_path
  end

  private
    def movie_params
      params.require(:movie).permit(:title, :description, :genre_id, :movie_img)
    end

    def find_movie
      @movie = Movie.find(params[:id])
    end
end

MovieReview/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_movie
  before_action :find_review, only: [:edit, :update, :destroy]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # Associate review with movie
    @review.movie_id = @movie.id
    # Associate review with logged_in user
    @review.user_id = current_user.id
    if @review.save
      redirect_to movie_path(@movie)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to movie_path(@movie)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to movie_path(@movie)
  end

  private
    def review_params
      params.require(:review).permit(:rating, :comment)
    end

    def find_movie
      @movie = Movie.find(params[:movie_id])
    end

    def find_review
      @review = Review.find(params[:id])
    end
end

MovieReview/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

MovieReview/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :index, :destroy]
  before_action :correct_user,   only: [:edit, :update]

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the ReView FLIX!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "Your account was deleted"
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in"
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

MovieReview/app/helpers/application_helper.rb
module ApplicationHelper
end

MovieReview/app/helpers/movies_helper.rb
module MoviesHelper
end

MovieReview/app/helpers/reviews_helper.rb
module ReviewsHelper
end

MovieReview/app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user?(user)
    user == current_user
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

MovieReview/app/helpers/users_helper.rb
module UsersHelper
end

MovieReview/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    
    <div class="navbar-header">
      <%= link_to "ReView FLIX", root_path, class: "navbar-brand" %>
    </div>

    <ul class="nav navbar-nav navbar-left">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Genres <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <% Genre.all.each do |gen| %>
            <li>
              <%= link_to gen.name, movies_path(genre: gen.name), class: "link" %>
            </li>
          <% end %>
        </ul>
      </li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Update", edit_user_path(current_user) %></li>
        <li><%= link_to "Sign Out", logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_path %></li>
        <li><%= link_to "Log In", login_path %></li>
      <% end %>
    </ul>

  </div>
</nav>

MovieReview/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieReview</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    
  </body>
</html>

MovieReview/app/views/movies/_form.html.erb
<%= form_for @movie, :html => { :multipart => true } do |f| %>

  <%= f.label :title %>:<br />
  <%= f.text_field :title, class: "form-control", placeholder: "Title" %><br />
  
  <%= f.label :description %>:<br />
  <%= f.text_area :description, class: "form-control", placeholder: "Description" %><br />
  
  <%= select_tag(:genre_id, options_for_select(@genres), :prompt => "Select a Genre") %><br />
  <%= f.file_field :movie_img %><br />

  <%= f.submit %>
  
<% end %>

MovieReview/app/views/movies/edit.html.erb
<h1>Edit Movie</h1>
<%= form_for @movie, :html => { :multipart => true } do |f| %>
  <%= f.label :title %>:<br />
  <%= f.text_field :title, class: "form-control" %><br />
  <%= f.label :description %>:<br />
  <%= f.text_area :description, class: "form-control" %><br />
  <%= f.select :genre_id, @genres %><br />
  <%= f.file_field :movie_img %><br />
  <%= f.submit %>
<% end %>

MovieReview/app/views/movies/index.html.erb
<% if logged_in? %>
  <%= link_to "Add Movie", new_movie_path, class: "btn btn-success" %>
<% end %>

<h1><%= params[:genre] %></h1>

<% if @movies.count == 0 %>

  <h3>There are no movies here. Add one!</h3>

<% else %>

  <div class="row">
    <% @movies.each do |movie| %>
      <div class="col-md-3 text-center">
        <a href="/movies/<%= movie.id %>">
          <%= image_tag movie.movie_img.url(:movie_index), class: "box-s" %>
        </a>
        <h4><%= movie.title %></h4>
      </div>
    <% end %>
  </div>
  
<% end %>

MovieReview/app/views/movies/new.html.erb
<h1>New Movie</h1>
<%= render 'form' %>

MovieReview/app/views/movies/show.html.erb
<div class="row">

  <div class="col-md-4">
    <%= image_tag @movie.movie_img.url(:movie_show), class: "box-s" %>
  </div>

  <div class="col-md-8">
    <h1><%= @movie.title %></h1>
    <h4>Genre: <%= @movie.genre.name %></h4>
    <p><%= @movie.description %></p>
    <p>Overall Rating</p>
    <div class="average-star-rating" data-score=<%= @average_review %>></div>
    <div class="avg-review">Based on <%= @movie.reviews.count %> reviews</div>
    
    <div>
      <% if logged_in? && @movie.user_id == current_user.id %>
        <%= link_to "Edit", edit_movie_path(@movie), class: "btn btn-success" %>
        <%= link_to "Delete", movie_path(@movie), method: :delete, data: {confirm: "Are you sure you want to delete this movie?"}, class: "btn btn-danger" %>
      <% end %>
      <%= link_to "View All Movies", root_path, class: "btn btn-primary" %>
    </div>

    <div class="reviews">
      <h4>Reviews</h4>
      <hr>
      <div>
        <% if @movie.reviews.length == 0 %>
          <p>No reviews yet. Add one!</p>
        <% else %>
          <%= render @movie.reviews %>
        <% end %>
        <% if logged_in? %>
          <%= link_to "Add Review", new_movie_review_path(@movie) %>
        <% end %>
      </div>
    </div>

  </div>
</div>

<script>
  $('.star-rating').raty({
    readOnly: true,
    score: function() {
      return $this.attr('data-score');
    },
    path: '/assets'
  });
</script>

<script>
  $('.average-star-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>

MovieReview/app/views/reviews/_form.html.erb
<%= form_for([@movie, @movie.reviews.build]) do |f| %>
  <div id="rating-form">
    <label>Rating</label>
  </div><br />
  <%= f.label :comment %>:<br />
  <%= f.text_area :comment, class: "form-control" %><br />
  <%= f.submit %>
<% end %>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

MovieReview/app/views/reviews/_review.html.erb
<div class="star-rating" data-score="<%= review.rating %>"></div>

<p><%= review.comment %></p>
<hr>

<% if logged_in? && review.user_id == current_user.id %>
    <%= link_to "Edit", edit_movie_review_path(review.movie, review), class: "btn btn-primary" %>
    <%= link_to "Delete", movie_review_path(review.movie, review), method: :delete, data: {confirm: "You want to delete your review?"}, class: "btn btn-danger" %>
<% end %>

MovieReview/app/views/reviews/edit.html.erb
<h1>Edit Review for: <%= @movie.title %></h1>
<%= form_for([@movie, @review]) do |f| %>
  <div id="rating-form">
    <label>Rating</label>
  </div><br />
  <%= f.label :comment %>:<br />
  <%= f.text_area :comment, class: "form-control" %><br />
  <%= f.submit %>
<% end %>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

MovieReview/app/views/reviews/new.html.erb
<h1>New Review</h1>
<%= render 'form' %>

MovieReview/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

MovieReview/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

MovieReview/app/views/users/edit.html.erb
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <%= link_to "Delete Account", @user, method: :delete, data: {confirm: "Are you sure you want to delete your account?"}, class: "btn btn-danger", style: "margin-top: 20px;" %>
  </div>
</div>

MovieReview/app/views/users/new.html.erb
<% provide(:button_text, 'Create my account') %>
<div class="text-center">
  <h1>Sign up</h1>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

MovieReview/app/views/users/show.html.erb
<h1>Profile</h1>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
    </section>
    <%= link_to "Update", edit_user_path(current_user), class: "btn btn-primary" %>
  </aside>
</div>